"""add categories table and category_id to transactions

Revision ID: 8a2b9c1d3e5f
Revises: 6aa55c033dea
Create Date: 2026-08-08 10:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8a2b9c1d3e5f'
down_revision: Union[str, None] = '6aa55c033dea'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'categories',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('name', sa.String(length=50), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
        sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_categories_id'), 'categories', ['id'], unique=False)
    op.add_column('transactions', sa.Column('category_id', sa.Integer(), nullable=True))
    op.create_foreign_key(
        'fk_transactions_category_id', 'transactions', 'categories',
        ['category_id'], ['id'], ondelete='SET NULL'
    )
    op.create_index(op.f('ix_transactions_category_id'), 'transactions', ['category_id'], unique=False)
    # ### end Alembic commands ###

    # Seed default categories (idempotent)
    connection = op.get_bind()
    category_table = sa.table(
        'categories',
        sa.column('id', sa.Integer),
        sa.column('name', sa.String),
        sa.column('created_at', sa.DateTime),
        sa.column('updated_at', sa.DateTime),
    )
    existing_count = connection.execute(
        sa.select(sa.func.count()).select_from(category_table)
    ).scalar()
    if existing_count == 0:
        op.bulk_insert(
            category_table,
            [
                {'name': 'Ăn uống'},
                {'name': 'Đi lại'},
                {'name': 'Nhà cửa'},
                {'name': 'Hóa đơn'},
                {'name': 'Giải trí'},
                {'name': 'Sức khỏe'},
                {'name': 'Mua sắm'},
                {'name': 'Giáo dục'},
                {'name': 'Du lịch'},
                {'name': 'Khác'},
            ],
        )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_transactions_category_id'), table_name='transactions')
    op.drop_constraint('fk_transactions_category_id', 'transactions', type_='foreignkey')
    op.drop_column('transactions', 'category_id')
    op.drop_index(op.f('ix_categories_id'), table_name='categories')
    op.drop_table('categories')
    # ### end Alembic commands ###
